name: Cypress Tests

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: npm run test:api
        env:
          REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}

      - name: Run UI tests
        run: npm run test:ui